Shop.create(name: "Purple Kow", address: "3620 Balboa St.", city: "San Francisco", state: "CA", zip: 94121)
Shop.create(name: "Tea Papa", address: "560 Balboa St.", city: "San Francisco", state: "CA", zip: 94118)
Shop.create(name: "Bubblecup", address: "1900 Clement St.", city: "San Francisco", state: "CA", zip: 94121)
Shop.create(name: "BAMBU", address: "6050 Geary Blvd.", city: "San Francisco", state: "CA", zip: 94121)
Shop.create(name: "The Sweet House", address: "3512 Balboa St.", city: "San Francisco", state: "CA", zip: 94121)
Shop.create(name: "Honey B Tea House", address: "2201 Clement St.", city: "San Francisco", state: "CA", zip: 94121)
Shop.create(name: "Xpresso Tea", address: "6901 Geary Blvd.", city: "San Francisco", state: "CA", zip: 94121)
Shop.create(name: "Sharetea", address: "5336 Geary Blvd.", city: "San Francisco", state: "CA", zip: 94121)
Shop.create(name: "InfiniTea", address: "5351 Geary Blvd.", city: "San Francisco", state: "CA", zip: 94121)
Shop.create(name: "E Tea", address: "5344 Geary Blvd.", city: "San Francisco", state: "CA", zip: 94121)
Shop.create(name: "Bottle Zup", address: "354 Clement St.", city: "San Francisco", state: "CA", zip: 94118)
Shop.create(name: "Mr & Mrs Tea House", address: "544 Clement St.", city: "San Francisco", state: "CA", zip: 94118)
Shop.create(name: "Sweet Hut", address: "519 Clement St.", city: "San Francisco", state: "CA", zip: 94118)
Shop.create(name: "Little Sweet", address: "3836 Geary Blvd.", city: "San Francisco", state: "CA", zip: 94118)
Shop.create(name: "Wonderful Dessert & Cafe", address: "2035 Irving St.", city: "San Francisco", state: "CA", zip: 94122)
Shop.create(name: "i-Tea", address: "2150 Irving St.", city: "San Francisco", state: "CA", zip: 94122)
Shop.create(name: "Tpumps", address: "1916 Irving St.", city: "San Francisco", state: "CA", zip: 94122)
Shop.create(name: "Quickly", address: "2116 Irving St.", city: "San Francisco", state: "CA", zip: 94122)
Shop.create(name: "Teaway", address: "2250 Irving St.", city: "San Francisco", state: "CA", zip: 94122)
Shop.create(name: "BB Tea Station", address: "1314 Noriega St.", city: "San Francisco", state: "CA", zip: 94122)
Shop.create(name: "TJ Cups", address: "2437 Noriega St.", city: "San Francisco", state: "CA", zip: 94122)
Shop.create(name: "Eggettes", address: "3136 Noriega St.", city: "San Francisco", state: "CA", zip: 94122)
Shop.create(name: "Bubble Tea & Dessert Cafe", address: "1788 32nd Ave.", city: "San Francisco", state: "CA", zip: 94122)
Shop.create(name: "Super Cue Cafe", address: "1139 Taraval St.", city: "San Francisco", state: "CA", zip: 94116)
Shop.create(name: "Tea FM", address: "1353 Taraval St.", city: "San Francisco", state: "CA", zip: 94116)